### ISSUE TITLE
Update pypi package from 1.0.6 to 1.0.7

### ISSUE THREAD

**Issue by Silas-Asamoah** [rysuds/dunebuggy#16]
#14 though this issue was resolved 19 days ago, the pypi package still uses the old `GRAPH_QL_URL` in[ v1.0.6](https://pypi.org/project/dunebuggy/1.0.6/), hence anyone using this has to clone the repo instead of just pip installing.

Appreciate it if the new changes get published. Thanks!

**Comment by rysuds** [comment]
Great callout!, will publish the new package

**Comment by rysuds** [comment]
Done!

**Comment by Silas-Asamoah** [comment]
Awesome thanks!
